# Uncomment next line and run `zprof` to profile zsh startup
# zmodload zsh/zprof

# DISABLE_MAGIC_FUNCTIONS="true"
# ZSH_DISABLE_COMPFIX=true

### Brew completions (https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh)
### Redundant due to brew plugin below
# if type brew &>/dev/null; then
#   eval "$(brew shellenv)"

#   # compinit is called somewhere else already
#   # autoload -Uz compinit
#   # compinit
# fi
### end Brew completions

# Path to your oh-my-zsh installation.
export ZSH="/Users/eduard/.oh-my-zsh"

ZSH_THEME="agnoster"

# _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

### nvm
# export NVM_DIR=~/.nvm
# zstyle ':omz:plugins:nvm' lazy true
### end nvm

plugins=(ansible autojump bgnotify brew command-not-found cp docker docker-compose extract genpass git git-extras gpg-agent gradle macos sudo terraform timer)

# RPROMPT='$(jenv_prompt_info)'" "'$(rbenv_prompt_info)'"$RPROMPT"

source $ZSH/oh-my-zsh.sh

DEFAULT_USER=eduard
prompt_context(){}

### jenv
function loadjenv() {
# 	export PATH="$HOME/.jenv/bin:$PATH"
#     eval "$(jenv init -)"
    source $ZSH/plugins/jenv/jenv.plugin.zsh
}
### end jenv

### jdk version
jdk() {
        version=$1
        export JAVA_HOME=$(/usr/libexec/java_home -v"$version");
        java -version
 }
 # jdk 17 2> /dev/null
 export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
 ###

### rbenv
function loadrbenv() {
    source $ZSH/plugins/rbenv/rbenv.plugin.zsh
}
### end rbenv

### pyenv
function loadpyenv() {
	if command -v pyenv 1>/dev/null 2>&1; then
	  eval "$(pyenv init -)"
	fi
}
### end pyenv

### kubectl
function loadkubectlcompletion() {
	if (( $+commands[kubectl] )); then
	    __KUBECTL_COMPLETION_FILE="${ZSH_CACHE_DIR}/kubectl_completion"

	    if [[ ! -f $__KUBECTL_COMPLETION_FILE || ! -s $__KUBECTL_COMPLETION_FILE ]]; then
	        kubectl completion zsh >! $__KUBECTL_COMPLETION_FILE
	    fi

	    [[ -f $__KUBECTL_COMPLETION_FILE ]] && source $__KUBECTL_COMPLETION_FILE

	    unset __KUBECTL_COMPLETION_FILE
	fi
}
### end kubectl

alias thermlog="pmset -g thermlog"

alias 'rm!'='env rm'
alias 'rm'='trash -F'

alias 'dcp'='docker-compose pause'
alias 'dcu'='docker-compose unpause'

alias 'gitsc'='git switch --create'
alias 'gi'='git'

alias 'scrcpyf'='adb devices -l | tail +2 | fzf -1 -0 --reverse --height 35% | cut -d" " -f1 | xargs scrcpy -s'

alias 'tailscale'='/Applications/Tailscale.app/Contents/MacOS/Tailscale'

bindkey -e
bindkey '[C' forward-word
bindkey '[D' backward-word
bindkey "\e\eOD" backward-word 
bindkey "\e\eOC" forward-word


export HISTFILESIZE=100000000
export HISTSIZE=1000000

export ANDROID_HOME=/Users/eduard/Library/Android/sdk
export ANDROID_SDK=$ANDROID_HOME

export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/tools/proguard/bin

export KOTLIN_HOME=$(brew --prefix kotlin)/libexec

function mkd() {
  mkdir -p $1 && cd $_
}

function set-studio-jdk() {
# call like: $ set-studio-jdk "/Applications/Android Studio.app"
    export JAVA_HOME=$1/Contents/jre/jdk/Contents/home/
}

function screenshot-ocr() {
	screencapture -i /tmp/tesseract.png
	tesseract /tmp/tesseract.png stdout | tr -d \\f | pbcopy
}

# autojump
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh
# end autojump

# zsh-autosuggestions
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# end zsh-autosuggestions

# fzf
source <(fzf --zsh)
# end fzf

# git-extras
source /opt/homebrew/opt/git-extras/share/git-extras/git-extras-completion.zsh
# end git-extras

# zsh-syntax-highlighting
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#end zsh-syntax-highlighting

# # 1Password CLI
# eval "$(op completion zsh)"; compdef _op op
# # end 1Password CLI

# OrbStack
# if (( $+commands[orbctl] )); then
#   eval "$(orbctl completion zsh)"
#   compdef _orb orbctl
#   compdef _orb orb
# fi
# end OrbStack

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# interactive ADB
# adapted from https://gist.github.com/zmdominguez/9a889f1c367e1a21203ce8527c81e612

# Sends an interactive ADB command
# Usage: Use the usual ADB command, replacing `adb` with `adbi`

function adbi() {
    local devices
    devices=$(adb devices -l | grep -v "unauthorized" | grep -E ".*?model:\S*" | \
              fzf -1 -0 --reverse --height 35% -m | cut -d" " -f1)

    if [[ -n "$devices" ]]; then
      for device in $devices; do
        if [[ "$1" == "shell" && $# -eq 1 ]]; then
          # Directly invoke shell to keep it interactive
          adb -s "$device" shell
        else
          adb -s "$device" "$@"
        fi
      done
    fi
}

# Display modes
alias darkMode='adbi shell cmd uimode night yes > /dev/null'
alias lightMode='adbi shell cmd uimode night no > /dev/null'

# Deep links
function deeplink() {
  adbi shell am start -W -a android.intent.action.VIEW -d \""$1"\"
}

export GPG_TTY=$(tty)

alias tldr='nocorrect tldr'
alias j='nocorrect j'

alias bringz='git pull'

# Wave config auto-added by bin/setup
source /Users/eduard/.waverc
